version: "3.9"
services:
  noteDb:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "note"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - note-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  note-data:
